Add clients component
For some reason this was automatically? added to server.index.js when I added cors:
const { default: App } = require('../client/src/App');

Had this error until I deleted the line:

[nodemon] app crashed - waiting for file changes before starting...
[nodemon] restarting due to changes...
[nodemon] starting `node server/index.js`
/PROJECT-MGMT-APP/client/src/App.js:1
import Header from "./components/Header";
^^^^^^

SyntaxError: Cannot use import statement outside a module